Cats99/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats
  resources :cat_rental_requests
end

Cats99/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Cats99/app/models/cat.rb
require 'date'
require 'action_view'
require 'action_view/helpers'

class Cat < ApplicationRecord
  include ActionView::Helpers::DateHelper
  COLORS = ['red', 'orange', 'yellow', 'green', 'blue', 'black']
  validates :color, inclusion: { in: COLORS , message: 'Color doesn\'t exist!' }, presence: true
  validates :sex, inclusion: { in: %w(M F), message: 'That is an invalid sex!' }, presence: true
  validates :birth_date, :name, :description, presence: true

  has_many :cat_rental_requests,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: 'CatRentalRequest'

  def age
    distance_of_time_in_words(DateTime.now, self.birth_date)
  end

end

Cats99/app/models/cat_rental_request.rb
require 'date'

class CatRentalRequest < ApplicationRecord
  STATUS = ['PENDING', 'APPROVED', 'DENIED']
  validates :status, inclusion: { in: STATUS, message: 'Invalid Status!' }, presence: true
  validates :cat_id, :start_date, :end_date, presence: true
  validate :does_not_overlap_approved_requests

  belongs_to :cat,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: 'Cat',
    dependent: :destroy

  def overlapping_requests
    CatRentalRequest.where(cat_id: cat_id).where("? BETWEEN start_date AND end_date AND ? BETWEEN start_date AND end_date", start_date, end_date).distinct
  end

  def overlapping_approved_requests
    overlapping_requests.where(status: "APPROVED")
  end

  def does_not_overlap_approved_requests
    errors[:date] << "Dates are overlapping!" if overlapping_approved_requests.exists?
  end
end

Cats99/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Cats99/app/controllers/catrentalrequests_controller.rb
class CatRentalRequestsController < ApplicationController
  def new
    @request = CatRentalRequest.new
    render :new
  end

  def create

  end

  private
end

Cats99/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render_error
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render_error
    end
  end

  private
  def cat_params
    params.require(:cat).permit(:birth_date, :color, :name, :sex, :description, :age)
  end

  def render_error
    render json: @cat.errors.full_messages, status: :unprocessable_entity
  end
end

Cats99/app/helpers/application_helper.rb
module ApplicationHelper
end

Cats99/app/views/catrentalrequests/_form.html.erb
<form action="<%= cat_rental_requests_url %>" method="post">
  <select name="cat_rental_request[cat_id]">

  </select>
</form>

Cats99/app/views/cats/_form.html.erb
<% action_url = cat.persisted? ? cat_url(@cat) : cats_url %>
<% form_method = cat.persisted? ? "patch" : "post" %>
<% submit_text = cat.persisted? ? "Edit this Cat" : "Create New Cat" %>
<form action=" <%= action_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="<%= form_method %>">
  <label for="name">Name</label>
    <input id="name" type="text" name="cat[name]" value="<%= @cat.name %>">
    <br>
  <label for="sex">Sex</label>
    M<input type="radio" name="cat[sex]" value="M" <%= @cat.sex == "M" ? "checked" : "" %>>
    F<input type="radio" name="cat[sex]" value="F" <%= @cat.sex == "F" ? "checked" : "" %>>
    <br>
  <label>
    Color
    <select name="cat[color]">
      <option value="default" disabled selected>--select a color--</option>
      <% Cat::COLORS.each do |color| %>
        <option value="<%= color %>" <%= @cat.color == color ? "selected" : "" %>><%= color %></option>
      <% end %>
    </select>
  </label>
    <br>
  <label for="birth_date">Birthday</label>
    <input type="date" name="cat[birth_date]" value="<%= @cat.birth_date %>">
  <br>
  <label for="description">Description</label>
    <textarea id="description" name="cat[description]"><%= @cat.description %></textarea>
  <br>
  <input type="submit" value="<%= submit_text %>">
</form>

Cats99/app/views/cats/edit.html.erb
<%= render "form", cat: @cat %>

Cats99/app/views/cats/index.html.erb
<h1>All the Cats</h1>
<ul>
  <% @cats.each do |cat| %>
    <li>
      <ul>
        <li><%= cat.name %></li>
        <li><%= cat.birth_date %></li>
        <li><%= cat.color %></li>
        <li><%= cat.sex %></li>
        <li><%= cat.description %></li>
      </ul>
      <br>
    </li>
  <% end %>
</ul>

Cats99/app/views/cats/new.html.erb
<%= render "form", cat: @cat %>

Cats99/app/views/cats/show.html.erb
<table>
  <thead>
    <tr>
      <th colspan='2'><%= @cat.name %></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Birthday</td>
      <td><%= @cat.birth_date %></td>
    </tr>
    <tr>
      <td>Color</td>
      <td> <%= @cat.color %></td>
    </tr>
    <tr>
      <td>Sex</td>
      <td> <%= @cat.sex %></td>
    </tr>
    <tr>
      <td>Age</td>
      <td> <%= @cat.age %></td>
    </tr>
    <tr>
      <td>Description</td>
      <td> <%= @cat.description %></td>
    </tr>
  </tbody>
</table>

Cats99/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats99</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>